{%- raw -%}
---
app_server: "{{ hostvars[app_name ~ '-dev']['ansible_eth1']['ipv4']['address'] }}"
nginx_server: "{{ app_server }}"
postgresql_server: "{{ app_server }}"
redis_server: "{{ app_server }}"
redis_cache_server: "{{ app_server }}"
{%- endraw -%}
