{%- raw -%}
---
  - name: install python-software-properties
    apt: pkg=python-software-properties state=present
    tags:
      - packages

  - name: install python
    apt: pkg={{ item }} state=installed
    with_items:
      - build-essential
      - python-dev
      - python-setuptools
    tags:
      - packages

  - name: install pip
    easy_install: name=pip
    tags:
      - packages

  - name: install/upgrade essential python packages
    pip: name={{ item }} state=latest
    with_items:
      - pip
      - setuptools
      - virtualenv
    tags:
      - packages

{%- endraw -%}
