{%- raw -%}
---
  - name: create gateone directories
    file: path={{ gateone_path }}/items state=directory
    with_items:
      - users

  - name: install python components
    pip: name={{ item }} state=latest virtualenv={{ gateone_path }}/venv
    with_items:
      - tornado
      - kerberos
    notify:
      - restart gateone

  - name: install supervisor runscript
    template: src=gateone.ini dest=/etc/supervisor/gateone.ini
    notify:
      - restart gateone

  - name: install from github
    pip: name="git+https://github.com/liftoff/GateOne#egg=GateOne"
    notify:
      - restart gateone

  - name: create /opt/gateone/conf.d
    file: path=/opt/gateone/conf.d state=directory

  - name: install config files
    template: src={{ item }} dest=/opt/gateone/conf.d/{{ item }}
    with_items:
      - 10server.conf
      - 20authentication.conf
      - 30api_keys.conf
    notify:
      - restart gateone

{%- endraw -%}
